---
- name: restart nginx
  ansible.builtin.command:
    cmd: |
      nginx -s stop
      nginx

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: reload nginx
  ansible.builtin.command:
    cmd: nginx -s reload
  when: nginx_service_state == "started"
